apiVersion: apps/v1
kind: Deployment
metadata:
  name: photosapplication-deployment
  labels:
    app: photos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: photos
  template:
    metadata:
      labels:
        app: photos
    spec:
      containers:
      - name: photos-application
        image: 347476671573.dkr.ecr.us-east-1.amazonaws.com/uat-bki-fe-test:latest
        ports:
        - containerPort: 80
