name: Build and Publish Docker Image to DockerHub
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: DockerHub Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/photosapp:v${{github.run_id}}
        
      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/photosapp:v${{github.run_id}}
      
      - name: Checkout GitOps Repository
        uses: actions/checkout@v2
        with:
          repository: bhuvanprasadg/argocd-test
          ref: main
          token: ${{ secrets.PAT }}

      - name: Update image version in manifest
        run: |
          cd dev/
          my_variable=$(sed -n '/^photosapp.*/p' deployment.yaml)
          sed -i "s/photosapp:v4530288290/photosapp:v${{github.run_id}}/g" deployment.yaml
  
      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add dev/deployment.yaml
          git commit -m "Update image version in deployment manifest"
          git push
